CREATE TABLE IF NOT EXISTS specialities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    budget_places INTEGER NOT NULL DEFAULT 0,
    paid_places INTEGER NOT NULL DEFAULT 0,
    admission_plan INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS admission_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id BIGINT NOT NULL,
    speciality_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    passport_series VARCHAR(255) NOT NULL,
    passport_number VARCHAR(255) NOT NULL,
    snils VARCHAR(255) NOT NULL,
    education_document_number VARCHAR(255) NOT NULL,
    graduation_school VARCHAR(255) NOT NULL,
    graduation_year INTEGER NOT NULL,
    points INTEGER NOT NULL,
    applicant_comment VARCHAR(2000),
    staff_comment VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_admission_applications_applicant FOREIGN KEY (applicant_id) REFERENCES app_users(id),
    CONSTRAINT fk_admission_applications_speciality FOREIGN KEY (speciality_id) REFERENCES specialities(id)
);

CREATE TABLE IF NOT EXISTS application_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL,
    data BYTEA NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_application_documents_application FOREIGN KEY (application_id) REFERENCES admission_applications(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_admission_applications_applicant_id ON admission_applications (applicant_id);
CREATE INDEX IF NOT EXISTS idx_admission_applications_speciality_id ON admission_applications (speciality_id);
CREATE INDEX IF NOT EXISTS idx_admission_applications_status ON admission_applications (status);
CREATE INDEX IF NOT EXISTS idx_application_documents_application_id ON application_documents (application_id);

INSERT INTO specialities (code, name, description, budget_places, paid_places, admission_plan, created_at)
VALUES
    ('09.02.07', 'Информационные системы и программирование', 'Подготовка разработчиков, администраторов и специалистов по цифровым сервисам.', 25, 15, 40, CURRENT_TIMESTAMP),
    ('38.02.01', 'Экономика и бухгалтерский учет', 'Работа с документами, учетом, аналитикой и финансовой отчетностью.', 20, 10, 30, CURRENT_TIMESTAMP),
    ('40.02.04', 'Юриспруденция', 'Подготовка специалистов по правовому сопровождению и документации.', 18, 12, 30, CURRENT_TIMESTAMP);

INSERT INTO app_users (full_name, username, password_hash, role, email, phone, active, created_at)
VALUES
    ('Администратор ПГК', 'admin', '{noop}admin123', 'ADMIN', 'admin@pgk.local', '+7 (900) 000-00-01', TRUE, CURRENT_TIMESTAMP),
    ('Сотрудник приемной комиссии', 'staff', '{noop}staff123', 'STAFF', 'staff@pgk.local', '+7 (900) 000-00-02', TRUE, CURRENT_TIMESTAMP);
