CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE specialities
    ADD COLUMN IF NOT EXISTS department_id BIGINT;

INSERT INTO departments (code, name, description, created_at)
VALUES
    ('IT', 'Информационных технологий', 'Подготовка разработчиков, администраторов и специалистов по цифровым сервисам.', CURRENT_TIMESTAMP),
    ('ECON', 'Экономики и управления', 'Подготовка специалистов по учету, финансам и управлению.', CURRENT_TIMESTAMP),
    ('LAW', 'Правовых дисциплин', 'Подготовка специалистов по правовому сопровождению и документации.', CURRENT_TIMESTAMP)
ON CONFLICT (code) DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description;

UPDATE specialities
SET department_id = (SELECT id FROM departments WHERE code = 'IT')
WHERE code = '09.02.07';

UPDATE specialities
SET department_id = (SELECT id FROM departments WHERE code = 'ECON')
WHERE code = '38.02.01';

UPDATE specialities
SET department_id = (SELECT id FROM departments WHERE code = 'LAW')
WHERE code = '40.02.04';

CREATE INDEX IF NOT EXISTS idx_specialities_department_id ON specialities (department_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_specialities_department'
    ) THEN
        ALTER TABLE specialities
            ADD CONSTRAINT fk_specialities_department
            FOREIGN KEY (department_id) REFERENCES departments(id);
    END IF;
END $$;

ALTER TABLE specialities
    ALTER COLUMN department_id SET NOT NULL;
