CREATE TABLE IF NOT EXISTS application_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_application_chat_messages_application FOREIGN KEY (application_id) REFERENCES admission_applications(id) ON DELETE CASCADE,
    CONSTRAINT fk_application_chat_messages_sender FOREIGN KEY (sender_id) REFERENCES app_users(id)
);

CREATE INDEX IF NOT EXISTS idx_application_chat_messages_application_id ON application_chat_messages (application_id);
CREATE INDEX IF NOT EXISTS idx_application_chat_messages_created_at ON application_chat_messages (created_at);
